<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<Description>Provides configuration and input data structures for various input devices (i.e. mice, keyboard, gamepad, etc.) and is meant to serve as an integration helper with an input integration library</Description>
		<PackageTags>OpenSourceKingdom, OpenSource, configuration, extension, input, device, control, controller, device, game, pad, throttle, joy, stick, map, action, key, scheme, definition</PackageTags>
		<Title>OSK.Petra.Extensions.Inputs.Devices</Title>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="OSK.Operations.Outputs" Version="1.4.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OSK.Extensions.Petra.Inputs.Configuration\OSK.Extensions.Petra.Inputs.Configuration.csproj" />
		<ProjectReference Include="..\OSK.Petra.Inputs.Abstractions\OSK.Petra.Inputs.Abstractions.csproj" />
	</ItemGroup>

</Project>
