using OSK.Petra.Inputs.Abstractions.Runtime;
using System;

namespace OSK.Petra.Inputs.Notifications;

/// <summary>
/// Notification transmitted when input is received from a device. This is a key part for an input integration to transmit to fully work with the input system.
/// </summary>
public class DeviceInputNotification(RuntimeDeviceIdentifier deviceIdentifier, long inputId, TimeSpan deltaTime, params IInputEvent[] inputEvents): DeviceNotification(deviceIdentifier)
{
    /// <summary>
    /// The input identifier associated with the device.
    /// </summary>
    public long InputId => inputId;

    /// <summary>
    /// The elapsed time since the last input update.
    /// </summary>
    public TimeSpan DeltaTime => deltaTime;

    /// <summary>
    /// The input events generated by the device.
    /// </summary>
    public IInputEvent[] InputEvents => inputEvents;
}
