<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<InternalsVisibleTo>OSK.Petra.Inputs.UnitTests</InternalsVisibleTo>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\OSK.Petra.Inputs.Abstractions\OSK.Petra.Inputs.Abstractions.csproj" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
		<PackageReference Include="OSK.DataStructures" Version="2.1.0" />
		<PackageReference Include="PolySharp" Version="1.16.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
